Add insecure repository support
bazelbuild/rules_docker pull request #1403
Opened 2020-01-28 21:47 UTC by fahhem

Local registries, such as microk8s, don't have SSL setup.

This PR just adds the ability to specify to push to an insecure repository. I'm not sure if that's the intended design pattern for this, so I'm open to suggestions!

2020-01-28 21:48 UTC, fahhem commented
/assign @smukherj1

2020-01-28 21:52 UTC, fahhem commented
This might also address #1245

2020-01-29 13:32 UTC, smukherj1 reviewed
Thanks for the PR! Do you mind adding a test [here](https://github.com/bazelbuild/rules_docker/blob/master/testing/e2e/pusher.sh) that exercises the new insecure_repository attribute?

2020-06-22 14:19 UTC, jake-arkinstall commented
Any update on this?

2021-01-25 06:59 UTC, asv commented
@fahhem will you finish this PR or can I post mine? For our production, this is a very important feature in rules_docker.

2021-01-25 16:36 UTC, fahhem commented
I don't have a publicly-available insecure repository available to add a test against. If you have a better PR, go ahead and post it, I'm not attached to this PR in any way. I was simply sharing what I had to do to get a on-machine docker repository to work.

2021-02-03 22:00 UTC, fahhem commented
I've rebased onto master. I don't know the test infra here, so I added a "test" that is probably wrong. :shrug: if anyone else has a better test or at least a suggestion on how to write one, I'm happy to swap mine out for it.

2022-08-22 16:51 UTC, cfife-btig commented
We are very interested in having this merged in. We are also dependent on a registry which is insecure and are having to write lots of workarounds without this change.

2022-09-26 06:24 UTC, fahhem commented
Rebased again. This time the tests are failing for the same reason the master tests are failing (something about an unsupported version of ubuntu?  `ubuntu2104` vs the mentioned `ubuntu1804`)

2022-10-18 01:50 UTC, fahhem commented
@uhthomas any chance this can be reviewed? It's a pretty small PR :)

2022-10-18 03:31 UTC, linzhp approved these changes
LGTM

2022-10-18 04:46 UTC, fahhem commented
@linzhp any idea on what I should do about the required-but-failing CI step? Or will you be able to merge it anyway?

2022-10-18 04:46 UTC, fahhem commented
Oh, and thank you!

2022-10-18 04:51 UTC, linzhp commented
It doesn't allow me to merge without CI passing

2022-10-18 13:32 UTC, uhthomas requested changes

2022-10-18 13:32 UTC, uhthomas commented on container/go/cmd/pusher/pusher.go
> +	var options = []name.Option{};
This needs to be run through gofmt, Go code does not typically have semi colons.

Also, it's usually preferred to write this as:

```go
var opts []name.Option
```

2022-10-18 13:32 UTC, uhthomas commented on container/go/cmd/pusher/pusher.go
> +		options = append(options, name.Insecure);
gofmt

2022-10-18 16:17 UTC, cfife-btig commented
I'm just happy to see some progress is on this MR :')

2022-10-18 18:05 UTC, fahhem commented
Same here :D Thanks @uhthomas, I ran gofmt and it had a couple more changes than around my code, but it was all whitespace stuff.

2022-10-18 23:14 UTC, fahhem commented
sorry for the noise, github's reviewer UI looks... strange. Anyone consider reviewable.io?

2022-10-29 01:35 UTC, fahhem commented
@uhthomas sorry to bother!

2022-11-03 22:00 UTC, cfife-btig commented
I don't mean to keep pecking either. But my team is also really interested in getting this merged in as well. I know that the CI is still being blocked but it sorta sounds like it just might be some sort of noise and not anything legitimate. Although of course I also have no visibility.

2022-11-03 23:00 UTC, uhthomas approved these changes

2022-11-03 23:01 UTC, uhthomas commented
Looks okay, we'll need to understand why CI isn't happy and then we can merge.

2022-11-04 02:19 UTC, fahhem commented
All PR's are blocked until CI is fixed? Is anyone at bazel working on fixing the CI?

It's a lot easier to fix buildkite stuff when you have access to the servers, but I can take a stab at it still.

2022-11-06 17:08 UTC, linzhp commented
Sorry for the delay. I just fixed CI (#2178)

2022-11-08 21:37 UTC, fahhem commented
Thank you @linzhp I fixed the tests too, so this PR should be ready to go!

2022-11-08 21:48 UTC, merged

2022-11-08 22:03 UTC, cfife-btig commented
🎉🎉🎉

2023-01-12 15:34 UTC, yc185050 commented
Any idea when will this be released? Waiting on this fix.

2023-01-17 06:33 UTC, fahhem commented
@yc185050 I recommend opening a new issue to request a release. Personally, I'm using master at that merged commit as my company's release while we wait for an official release

2026-01-27 09:13 UTC, matthewei commented
Hi , how can we use this feature?