Sluongngoc/push all check digest
bazelbuild/rules_docker pull request #1744
Opened 2021-03-02 23:17 UTC by sluongng

## Bring push-all on par with container_push in term of feature parity.

Generally `--skip-unchanged-digest` is a very useful flag to have. One can simply setup a release pipeline upon successful CI to just do `bazel run <push-all-target>` to push all container images (wrapped in a container bundle) at once.

By checking against upstream registry whether an existing digest already existed, we will only push images which were updated as the result of recent changes introduced to the repo.

The alternative solution is to calculate the SCM diff (git-diff) of the repo to deduce which bazel target were affected, query for container_push targets and `bazel run` each target 1-by-1, which is complicated to setup (especially when handling deleted code).

---

This PR added the ability to verify unchanged digest to bundle push (contrib/push-all) rule for convenience.

Without this, the ability to skip unchanged digest is exclusive to container_push and one would need something like https://github.com/atlassian/bazel-tools/tree/master/multirun to achieve the equivalent.

Caveats: when push-all with a container bundle that has duplicated images and push-all is set to run in parallel, the final result might be random. Use sequential push option if you think this is an issue.

2021-03-02 23:20 UTC, sluongng commented
I did split this PR into 3 separate commits for easier review.

This closes https://github.com/bazelbuild/rules_docker/issues/1741

2021-03-03 17:26 UTC, sluongng commented
/assign @smukherj1

2021-03-12 22:23 UTC, sluongng commented
@alexeagle it would be nice to get this reviewed / merge 🙏

2021-03-13 10:28 UTC, zoidbergwill commented
Maybe splitting the commits into separate PRs will make it easier / safer to merge?

2021-03-31 15:29 UTC, pcj requested changes
Thanks @sluongng this looks like a useful addition.  I think it will need some documentation about the behaviour as it may surprise people when upgrading.

2021-03-31 15:29 UTC, pcj commented on contrib/push-all.bzl
> -    stamp_arg = " ".join(["--stamp-info-file=%s" % _get_runfile_path(ctx, f) for f in stamp_inputs])
Why is this line no longer needed?

2021-03-31 20:16 UTC, pcj commented on contrib/push-all.bzl
> -    stamp_arg = " ".join(["--stamp-info-file=%s" % _get_runfile_path(ctx, f) for f in stamp_inputs])
OK thanks for clarifying

2021-04-01 07:29 UTC, sluongng commented
> Thanks @sluongng this looks like a useful addition. I think it will need some documentation about the behaviour as it may surprise people when upgrading.

@pcj hey, regarding documentation improvement, do you have any recommendation?

I look back at the change and see that:
- This is not anyway breaking, all the current functionality remains to be the same
- New feature `skip_unchanged_digest` was added with a default value set to False (disable) and accompanied with starlark doc.

Reviewing https://github.com/bazelbuild/rules_docker/search?q=push-all there is not a lot of other references that needed to be updated. 🤔  Am I missing a generated markdown somewhere?

2021-05-09 17:01 UTC, sluongng commented
I just force pushed the PR to update according to feedback from Slack.

Changes from last round:
1. Drop the cleanup commits, will be sending them as a separate PR.

The diff is now expected to be small without noise.

2021-05-27 01:50 UTC, sluongng commented
@alexeagle ping

2021-12-03 10:02 UTC, sluongng commented
Rebase to origin/master + changed my email so that CLA passed

2021-12-03 10:06 UTC, sluongng commented
Switched from using `+= ["element"]` to `list.append("elelement")` to fix buildifier lint check

2021-12-03 17:05 UTC, alexeagle approved these changes

2021-12-03 17:06 UTC, alexeagle commented
I think there's still a sharp edge here - if you use stamping, then the image will be different on every build regardless of code changes. So we might want to document it a bit more - but since I just changed the stamping logic to require explicit opt-in (either via stamp = always or `--stamp`) I'm not as concerned as I would have been previously.

2021-12-03 17:44 UTC, sluongng commented
> I think there's still a sharp edge here - if you use stamping, then the image will be different on every build regardless of code changes. So we might want to document it a bit more - but since I just changed the stamping logic to require explicit opt-in (either via stamp = always or `--stamp`) I'm not as concerned as I would have been previously.

The great thing about OCI format and container registry is that even with stamping, _hopefully_ only the final image of the layer / the json manifest file / the final image tag in the sh_binary push script is affected content wise. In such cases, one should still be comfortable pushing all with minimal storage impacts onto the container registry.

Obviously keeping container images healthy by having re-useable layers will take some effort and not trivial, but it should be do-able if you set it up correctly.

2021-12-03 23:17 UTC, pcj commented
Hi @sluongng, approving this.  I think the `doc` on the attribute is enough documentation, though you probably didn't need to mention the default.

2021-12-03 23:17 UTC, pcj approved these changes

2021-12-04 23:34 UTC, merged