Base stamping decisions on --stamp configuration, not attributes on t…
bazelbuild/rules_docker pull request #1878
Opened 2021-06-02 19:42 UTC by alexeagle

…he rule

This follows the example of rules_go and rules_nodejs.

It means we don't produce cache-busting outputs unless the user
explicitly requests non-deteriminism in the build with --stamp.

BREAKING CHANGE:
- To get stamped outputs, users must now call bazel with `--stamp`
- the stamp attribute was removed from some providers
- the stamp attribute was deprecated on container_push and container_bundle, it is now removed
- the stamp attribute was removed from container_image, there is no
replacement

Fixes #1451

2021-06-03 00:09 UTC, gravypod requested changes
Could we add an update to [README.md](BUILD_CONTEXT_ATTRS) that explains this behavior?

2021-06-05 18:29 UTC, gravypod approved these changes
I think this is good but as we discussed we should wait for a major version change whenever we're ready.

2021-06-05 20:13 UTC, alexeagle commented
Okay so what's our cadence for major releases?
Since we haven't released a 1.0 semver dictates that breaking changes are in every minor. So we don't have a way to signal this beyond either just a 0.18.0 including this change.
I think we should have a 1.0. Could discuss doing that now? holding this change for that doesn't make a difference for semver though

2021-06-05 21:03 UTC, gravypod commented
Sounds good. I can luck off a 1.0 on Monday if you're ok with that? Let's
also check in with pcj but in my opinion this is fine.

On Sat, Jun 5, 2021, 4:13 PM Alex Eagle ***@***.***> wrote:

> Okay so what's our cadence for major releases?
> Since we haven't released a 1.0 semver dictates that breaking changes are
> in every minor. So we don't have a way to signal this beyond either just a
> 0.18.0 including this change.
> I think we should have a 1.0. Could discuss doing that now? holding this
> change for that doesn't make a difference for semver though
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/bazelbuild/rules_docker/pull/1878#issuecomment-855290035>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAG4HW6MZ47WTRL4OCC6NVLTRKAP7ANCNFSM457LHFEQ>
> .
>

2021-06-06 02:59 UTC, alexeagle commented
If we do 1.0 we need to say what that means and how we'll version in the future. Can discuss at our meeting Monday but I'll have to duck out early due to conflict

2021-11-25 05:24 UTC, alexeagle commented on README.md
> +Stamping is enabled when bazel is run with `--stamp`.
Updated this to still have a `stamp` attribute on our three stamp-aware rules, and that attribute is now a trinary. So you can still use stamp=always behavior like before.

2021-11-25 05:27 UTC, alexeagle commented
fyi @aptenodytes-forsteri rebased and landable.

2021-11-26 18:42 UTC, merged