Update to a more recent rules rust and update to use defs.bzl
bazelbuild/rules_docker pull request #1951
Opened 2021-11-05 19:49 UTC by dfreese

Rules rust has made some changes upstream that remove the rust.bzl file.
It had previously been left in there for compatibility purposes.  This
has been ongoing since February 16th.  See this issue for additional
context: https://github.com/bazelbuild/rules_rust/issues/591.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

2021-11-05 19:49 UTC, dfreese commented
@UebelAndre, FYI.

2021-11-05 19:53 UTC, UebelAndre commented
Thanks for picking this up!

Just for the paper trail, this PR would also close https://github.com/bazelbuild/rules_docker/issues/1949

2021-11-05 22:53 UTC, alexeagle commented
@dfreese are you working on the CI failure on Mac?

2021-11-05 23:07 UTC, dfreese commented
> @dfreese are you working on the CI failure on Mac?

No.  Given #1948, CI for make appears generally broken.

2021-11-06 00:59 UTC, dfreese commented
> > @dfreese are you working on the CI failure on Mac?
> 
> No. Given #1948, CI for ~make~ mac appears generally broken.

(so I'd have no idea what I'd be trying to fix with what looks like just sha values changing)

2021-11-07 15:59 UTC, UebelAndre requested changes

2021-11-07 15:59 UTC, UebelAndre commented on WORKSPACE
> +        # Master branch as of 2021-11-05
One small nit
```suggestion
        # `main` branch as of 2021-11-05
```

2021-11-07 21:16 UTC, gravypod commented
@UebelAndre & @

2021-11-07 21:16 UTC, closed without merging

2021-11-08 14:45 UTC, UebelAndre commented
@dfreese Can you reopen this PR and rebase?

2021-11-08 15:50 UTC, dfreese commented
couldn't reopen.  Not sure if it's because I force-pushed before trying to open again.  Regardless #1955 replaces this.