container_run_* rules silent on success
bazelbuild/rules_docker pull request #2027
Opened 2022-02-17 19:52 UTC by alexeagle

Prevents RunAndCommitLayer and related actions from spamming the Bazel stdout log with Docker output, when the action succeeds. Similar to #1969 which did this for ExtractImageId.

Fixes #2006

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2022-02-28 23:44 UTC, ptarjan commented
Thanks so much for fixing this! What's the process to get it merged?

2022-03-01 00:19 UTC, alexeagle commented
Need a review ... the maintainership on this repo is stretched very thin right now. @gravypod any response on your internal email thread about that?

2022-03-01 00:34 UTC, ptarjan commented
Thanks. I can verify it does indeed fix all the issues in the linked issue for us.

2022-03-03 22:05 UTC, alexeagle commented
Note, @ptarjan reports there are two more cases to fix:

```
$ bazel build bazel/docker/internal/test/image_with_packages_download.tar
INFO: Invocation ID: a91cc674-678a-4099-942e-d2c3ae98ea37
INFO: Analyzed target //bazel/docker/internal/test:image_with_packages_download.tar (66 packages loaded, 10815 targets configured).
INFO: Found 1 target...
INFO: From Action bazel/docker/internal/test/image_with_packages_download.tar:
Loaded image: bazel/bazel/docker/internal/test:ubuntu_image
37f4acdb6845a63e8dce1d1b5a02d0c179c779bb24b2b760e41556ffbfe74788
Target //bazel/docker/internal/test:image_with_packages_download.tar up-to-date:
  bazel-bin/bazel/docker/internal/test/image_with_packages_download.tar
INFO: Elapsed time: 28.350s, Critical Path: 16.55s
INFO: 76 processes: 56 disk cache hit, 20 internal.
INFO: Build completed successfully, 76 total actions
```
which I think is from container_image and

```
$ bazel bazel/docker/internal/test/image_with_packages_install.tar
INFO: Invocation ID: df0a3773-472e-4079-a136-2063ffcd9240
INFO: Analyzed 1 target (1 packages loaded, 9 targets configured).
INFO: Found 1 target...
INFO: From ExtractImageId bazel/docker/internal/test/image_with_packages_install.tar.unstripped:
Loaded image: bazel/bazel/docker/internal/test:ubuntu_image
Target //bazel/docker/internal/test:image_with_packages_install.tar up-to-date:
  bazel-bin/bazel/docker/internal/test/image_with_packages_install.tar
INFO: Elapsed time: 5.167s, Critical Path: 4.65s
INFO: 12 processes: 2 disk cache hit, 10 internal.
INFO: Build completed successfully, 12 total actions
```
which I think is from install_pkgs

2022-03-14 16:46 UTC, mattem requested changes

2022-03-14 16:46 UTC, mattem commented on docker/util/commit.sh.tpl
> +    if docker start -a "${id}"; then
```suggestion
    if $DOCKER $DOCKER_FLAGS start -a "${id}"; then
```

2022-03-15 00:34 UTC, mattem approved these changes

2022-03-22 22:33 UTC, alexeagle commented
replaced by #2047

2022-03-22 22:33 UTC, closed without merging