Run script allows empty docker_args
bazelbuild/rules_docker pull request #2053
Opened 2022-03-29 16:01 UTC by illicitonion

Currently when using `bazel run` on a docker image, I get:
```
/[redacted].executable: line 281: docker_args[@]: unbound variable
```

Alternatively, we could just `set +u` before execing docker.

2022-04-18 20:27 UTC, mindaugasrukas requested changes

2022-04-18 20:27 UTC, mindaugasrukas commented on container/incremental_load.sh.tpl
> +  # Bash treats empty arrays as unset variables for the purposes of `set -u` - work around this.
nit: to be clear, `set -u` is not an issue but a kinda runtime linter. So this is not a workaround but a bug fix. Could you rephrase the comment to look not like a workaround?

2022-04-18 20:27 UTC, mindaugasrukas commented on container/incremental_load.sh.tpl
> +  fi
Please use the original form of `"${container_args[@]:-}"` or remove the `else` part. As if it's not set, it is empty but not `-`:
For more details, please see https://tldp.org/LDP/abs/html/parameter-substitution.html

2022-04-19 10:06 UTC, illicitonion commented
Thanks for the review @mindaugasrukas - updated, PTAL!

2022-04-19 16:53 UTC, mindaugasrukas approved these changes
LGTM

2022-04-19 16:55 UTC, linzhp approved these changes

2022-04-19 16:55 UTC, merged