Add config flag to further disable transition effects caused by bazel pre-5.0 support
bazelbuild/rules_docker pull request #2103
Opened 2022-06-03 21:02 UTC by bduffany

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2022-06-03 21:04 UTC, bduffany commented
This is an attempt to address an issue that even when setting `--@io_bazel_rules_docker//transitions:enable=no`, we still get some config differences across targets built as a docker image dep, and targets not built as a docker image dep. This appears to be caused by this support for Bazel pre-5.0.

Looking for some initial feedback as to whether this approach seems reasonable -- if so, I can add tests.

2022-06-06 15:17 UTC, bduffany commented
@laurynaslubys @uhthomas Wondering if either of you have any thoughts on this PR? (The description includes some context)

2022-06-07 10:35 UTC, laurynaslubys requested changes
I'm not really comfortable with this suggestion. There are probably more things that could be streamlined if bazel < 5 was dropped. You could just have a small patch for this in your workspace I think.

2022-06-07 10:44 UTC, uhthomas commented
There is a `native.bazel_version` which could be used instead.

Really though, I would recommend upgrading to the latest version of Bazel. Is there anything preventing you from doing so?

2022-06-08 20:25 UTC, bduffany commented
@laurynaslubys that's understandable. Are there any plans for rules_docker to drop pre-5.0 support in the near-term future?

If not, I'm open to other ideas -- it would be nice to find some workaround that doesn't require a patch. For other folks using this flag, it'd be nice if the transition effects could be fully disabled so that builds both as a docker dep or not can be built in the same configuration (which has implications for caching, checksums, etc.)

@uhthomas It looks as though `native.bazel_version` only works in a repository context. (I tried using it and got an error.) Also, I am on the latest version of Bazel -- the problem is that this code which is intended to support earlier versions of Bazel is causing a configuration difference (the directory becomes `bazel-out-ST-{HASH}` instead of `bazel-out`).

2023-01-06 02:36 UTC, closed without merging